window.EXTRA_WORDS = [
  { id: 51, word: "ကျွန်တော်", phonetic: "kyun taw", meaning: "我（男性说法）", example: "ကျွန်တော် တရုတ်လူမျိုးပါ။", exampleCn: "我是中国人。" },
  { id: 52, word: "ကျွန်မ", phonetic: "kyun ma", meaning: "我（女性说法）", example: "ကျွန်မ ဒီမှာ နေပါတယ်။", exampleCn: "我住在这里。" },
  { id: 53, word: "ခင်ဗျား", phonetic: "khin bya", meaning: "你 / 您", example: "ခင်ဗျား နားလည်ပါသလား။", exampleCn: "您明白吗？" },
  { id: 54, word: "သူ", phonetic: "thu", meaning: "他 / 她", example: "သူ ဒီမှာ အလုပ်လုပ်ပါတယ်။", exampleCn: "他/她在这里工作。" },
  { id: 55, word: "ကျွန်တော်တို့", phonetic: "kyun taw doh", meaning: "我们", example: "ကျွန်တော်တို့ အတူတူ သွားမယ်။", exampleCn: "我们一起去。" },
  { id: 56, word: "သူတို့", phonetic: "thu doh", meaning: "他们", example: "သူတို့ ရုံးထဲမှာ ရှိပါတယ်။", exampleCn: "他们在办公室里。" },
  { id: 57, word: "ဘာလဲ", phonetic: "ba le", meaning: "是什么", example: "ဒါ ဘာလဲ။", exampleCn: "这是什么？" },
  { id: 58, word: "ဘာကြောင့်လဲ", phonetic: "ba jaung le", meaning: "为什么", example: "ဘာကြောင့် စောင့်ရမလဲ။", exampleCn: "为什么需要等？" },
  { id: 59, word: "ဘယ်လိုလဲ", phonetic: "be lo le", meaning: "怎么样 / 怎么做", example: "ဒီဖောင်ကို ဘယ်လို ဖြည့်ရမလဲ။", exampleCn: "这张表怎么填？" },
  { id: 60, word: "ဘယ်သူလဲ", phonetic: "be thu le", meaning: "是谁", example: "တာဝန်ခံ ဘယ်သူလဲ။", exampleCn: "负责人是谁？" },
  { id: 61, word: "ဘယ်အချိန်လဲ", phonetic: "be a chain le", meaning: "什么时候", example: "ဘယ်အချိန် ပြန်လာရမလဲ။", exampleCn: "什么时候需要回来？" },
  { id: 62, word: "ဘယ်နှစ်ခုလဲ", phonetic: "be hna khu le", meaning: "几个", example: "မိတ္တူ ဘယ်နှစ်ခု လိုပါသလဲ။", exampleCn: "需要几份复印件？" },
  { id: 63, word: "ဒီ", phonetic: "di", meaning: "这个", example: "ဒီ စာရွက် လိုပါတယ်။", exampleCn: "需要这份文件。" },
  { id: 64, word: "အဲဒီ", phonetic: "eh di", meaning: "那个", example: "အဲဒီ အခန်းကို သွားပါ။", exampleCn: "请去那个房间。" },
  { id: 65, word: "ဒီမှာ", phonetic: "di hma", meaning: "在这里", example: "ဒီမှာ လက်မှတ်ထိုးပါ။", exampleCn: "请在这里签名。" },
  { id: 66, word: "အဲဒီမှာ", phonetic: "eh di hma", meaning: "在那里", example: "အဲဒီမှာ စောင့်ပါ။", exampleCn: "请在那里等。" },
  { id: 67, word: "ရှိပါတယ်", phonetic: "shi ba de", meaning: "有 / 在", example: "ချိန်းဆိုချက် ရှိပါတယ်။", exampleCn: "我有预约。" },
  { id: 68, word: "မရှိပါဘူး", phonetic: "ma shi ba bu", meaning: "没有 / 不在", example: "မိတ္တူ မရှိပါဘူး။", exampleCn: "我没有复印件。" },
  { id: 69, word: "ရပါတယ်", phonetic: "ya ba de", meaning: "可以", example: "ဒီမှာ ပေးလို့ ရပါတယ်။", exampleCn: "可以在这里交。" },
  { id: 70, word: "မရပါဘူး", phonetic: "ma ya ba bu", meaning: "不可以", example: "ဒီနေ့ မရပါဘူး။", exampleCn: "今天不可以。" },
  { id: 71, word: "သွားမယ်", phonetic: "thwa me", meaning: "要去", example: "အစိုးရရုံးကို သွားမယ်။", exampleCn: "我要去政府办公室。" },
  { id: 72, word: "လာမယ်", phonetic: "la me", meaning: "会来", example: "မနက်ဖြန် ပြန်လာမယ်။", exampleCn: "明天我会再来。" },
  { id: 73, word: "ပြန်လာပါ", phonetic: "pyan la ba", meaning: "请回来 / 请再来", example: "မွန်းလွဲပိုင်း ပြန်လာပါ။", exampleCn: "请下午再来。" },
  { id: 74, word: "ဝင်ပါ", phonetic: "win ba", meaning: "请进", example: "အခန်းထဲ ဝင်ပါ။", exampleCn: "请进房间。" },
  { id: 75, word: "ထွက်ပါ", phonetic: "htwet ba", meaning: "请出去 / 出口", example: "ဒီတံခါးကနေ ထွက်ပါ။", exampleCn: "请从这个门出去。" },
  { id: 76, word: "ထိုင်ပါ", phonetic: "htaing ba", meaning: "请坐", example: "ဒီမှာ ထိုင်ပါ။", exampleCn: "请坐在这里。" },
  { id: 77, word: "ရပ်ပါ", phonetic: "yat ba", meaning: "请停 / 停下", example: "ဒီမှာ ရပ်ပါ။", exampleCn: "请在这里停。" },
  { id: 78, word: "ရေးပါ", phonetic: "yay ba", meaning: "请写", example: "နာမည်ကို ဒီမှာ ရေးပါ။", exampleCn: "请把名字写在这里。" },
  { id: 79, word: "ဖတ်ပါ", phonetic: "hpat ba", meaning: "请读", example: "ဒီစာကို ဖတ်ပါ။", exampleCn: "请读这段文字。" },
  { id: 80, word: "ကြည့်ပါ", phonetic: "kyi ba", meaning: "请看", example: "ဒီနေရာကို ကြည့်ပါ။", exampleCn: "请看这个地方。" },
  { id: 81, word: "ပေးပါ", phonetic: "pay ba", meaning: "请给", example: "စာရွက်စာတမ်း ပေးပါ။", exampleCn: "请给我文件。" },
  { id: 82, word: "ယူပါ", phonetic: "yu ba", meaning: "请拿 / 取", example: "နံပါတ်စာရွက် ယူပါ။", exampleCn: "请拿号码纸。" },
  { id: 83, word: "ပြပါ", phonetic: "pya ba", meaning: "请出示 / 请给看", example: "နိုင်ငံကူးလက်မှတ် ပြပါ။", exampleCn: "请出示护照。" },
  { id: 84, word: "စစ်ပါ", phonetic: "sit ba", meaning: "请检查", example: "စာရွက်တွေ စစ်ပါ။", exampleCn: "请检查文件。" },
  { id: 85, word: "ဖြည့်ပါ", phonetic: "hpyi ba", meaning: "请填写", example: "ဖောင်ကို ဖြည့်ပါ။", exampleCn: "请填写表格。" },
  { id: 86, word: "လက်မှတ်ထိုးပါ", phonetic: "let hmat htoe ba", meaning: "请签名", example: "အောက်မှာ လက်မှတ်ထိုးပါ။", exampleCn: "请在下面签名。" },
  { id: 87, word: "ပေးချေပါ", phonetic: "pay chay ba", meaning: "请付款", example: "ကောင်တာမှာ ပေးချေပါ။", exampleCn: "请在柜台付款。" },
  { id: 88, word: "ကောင်တာ", phonetic: "counter", meaning: "柜台", example: "ကောင်တာ နံပါတ် နှစ်ကို သွားပါ။", exampleCn: "请去二号柜台。" },
  { id: 89, word: "ဝန်ထမ်း", phonetic: "wun htan", meaning: "工作人员", example: "ဝန်ထမ်းကို မေးပါ။", exampleCn: "请问工作人员。" },
  { id: 90, word: "တာဝန်ခံ", phonetic: "ta wun khan", meaning: "负责人", example: "တာဝန်ခံနဲ့ တွေ့ချင်ပါတယ်။", exampleCn: "我想见负责人。" },
  { id: 91, word: "ဌာန", phonetic: "hta na", meaning: "部门", example: "လူဝင်မှုကြီးကြပ်ရေး ဌာန ဘယ်မှာလဲ။", exampleCn: "移民部门在哪里？" },
  { id: 92, word: "လူဝင်မှုကြီးကြပ်ရေး", phonetic: "lu win hmu gyi kyat yay", meaning: "移民局 / 移民事务", example: "လူဝင်မှုကြီးကြပ်ရေးရုံးကို သွားချင်ပါတယ်။", exampleCn: "我想去移民局。" },
  { id: 93, word: "အခွန်", phonetic: "a khun", meaning: "税", example: "အခွန်ဆောင်ရမလား။", exampleCn: "需要交税吗？" },
  { id: 94, word: "ဘဏ်", phonetic: "ban", meaning: "银行", example: "ဘဏ် ဘယ်မှာလဲ။", exampleCn: "银行在哪里？" },
  { id: 95, word: "ငွေလဲ", phonetic: "ngwe le", meaning: "换钱 / 兑换", example: "ငွေလဲချင်ပါတယ်။", exampleCn: "我想换钱。" },
  { id: 96, word: "ဘောက်ချာ", phonetic: "voucher", meaning: "收据 / 凭证", example: "ဘောက်ချာ ပေးပါ။", exampleCn: "请给我收据。" },
  { id: 97, word: "အတည်ပြု", phonetic: "a ti pyu", meaning: "确认", example: "အတည်ပြု ပေးပါ။", exampleCn: "请帮我确认。" },
  { id: 98, word: "မိတ္တူကူး", phonetic: "mi tu ku", meaning: "复印", example: "ဒီစာရွက် မိတ္တူကူးချင်ပါတယ်။", exampleCn: "我想复印这份文件。" },
  { id: 99, word: "ဓာတ်ပုံ", phonetic: "dat pone", meaning: "照片", example: "ဓာတ်ပုံ နှစ်ပုံ လိုပါတယ်။", exampleCn: "需要两张照片。" },
  { id: 100, word: "အရွယ်အစား", phonetic: "a ywe a sa", meaning: "尺寸 / 大小", example: "ဓာတ်ပုံ အရွယ်အစား ဘယ်လောက်လဲ။", exampleCn: "照片尺寸是多少？" },
  { id: 101, word: "မနက်", phonetic: "ma net", meaning: "早上", example: "မနက် ကိုးနာရီ လာပါ။", exampleCn: "请早上九点来。" },
  { id: 102, word: "နေ့လယ်", phonetic: "nei le", meaning: "中午", example: "နေ့လယ်မှာ ပိတ်ပါတယ်။", exampleCn: "中午会关门。" },
  { id: 103, word: "ညနေ", phonetic: "nya nay", meaning: "傍晚 / 下午晚些时候", example: "ညနေ ပြန်လာပါ။", exampleCn: "请傍晚再来。" },
  { id: 104, word: "ည", phonetic: "nya", meaning: "晚上", example: "ညမှာ မဖွင့်ပါဘူး။", exampleCn: "晚上不开门。" },
  { id: 105, word: "အခုချက်ချင်း", phonetic: "a khu chet chin", meaning: "马上 / 现在立刻", example: "အခုချက်ချင်း လုပ်လို့ရမလား။", exampleCn: "现在马上可以办吗？" },
  { id: 106, word: "ခဏ", phonetic: "kha na", meaning: "一会儿", example: "ခဏ စောင့်ပါ။", exampleCn: "请稍等一会儿。" },
  { id: 107, word: "နောက်မှ", phonetic: "nauk hma", meaning: "以后 / 稍后", example: "နောက်မှ ပြန်လာပါမယ်။", exampleCn: "我稍后再来。" },
  { id: 108, word: "အရင်", phonetic: "a yin", meaning: "先 / 以前", example: "အရင် ဖောင်ဖြည့်ပါ။", exampleCn: "请先填表。" },
  { id: 109, word: "ပြီးမှ", phonetic: "pi hma", meaning: "之后", example: "ပြီးမှ ကောင်တာကို သွားပါ။", exampleCn: "之后请去柜台。" },
  { id: 110, word: "နေ့တိုင်း", phonetic: "nei taing", meaning: "每天", example: "နေ့တိုင်း ဖွင့်ပါသလား။", exampleCn: "每天都开门吗？" },
  { id: 111, word: "တနင်္လာနေ့", phonetic: "ta nin la nei", meaning: "星期一", example: "တနင်္လာနေ့ လာပါ။", exampleCn: "请星期一来。" },
  { id: 112, word: "သောကြာနေ့", phonetic: "thaw kya nei", meaning: "星期五", example: "သောကြာနေ့ ပိတ်ပါသလား။", exampleCn: "星期五关门吗？" },
  { id: 113, word: "ပိတ်ပါတယ်", phonetic: "peik ba de", meaning: "关门 / 关闭", example: "ဒီနေ့ ရုံး ပိတ်ပါတယ်။", exampleCn: "今天办公室关门。" },
  { id: 114, word: "ဖွင့်ပါတယ်", phonetic: "hpwint ba de", meaning: "开门 / 开放", example: "မနက် ကိုးနာရီ ဖွင့်ပါတယ်။", exampleCn: "早上九点开门。" },
  { id: 115, word: "ဘယ်ဘက်", phonetic: "be bet", meaning: "左边", example: "ဘယ်ဘက်ကို ကွေ့ပါ။", exampleCn: "请往左转。" },
  { id: 116, word: "ညာဘက်", phonetic: "nya bet", meaning: "右边", example: "ညာဘက်မှာ ရုံး ရှိပါတယ်။", exampleCn: "办公室在右边。" },
  { id: 117, word: "ရှေ့", phonetic: "shay", meaning: "前面", example: "ရှေ့မှာ ကောင်တာ ရှိပါတယ်။", exampleCn: "前面有柜台。" },
  { id: 118, word: "နောက်", phonetic: "nauk", meaning: "后面", example: "နောက်မှာ တန်းစီပါ။", exampleCn: "请在后面排队。" },
  { id: 119, word: "အနီးမှာ", phonetic: "a ni hma", meaning: "附近", example: "အနီးမှာ ဘဏ် ရှိပါသလား။", exampleCn: "附近有银行吗？" },
  { id: 120, word: "အဝေးမှာ", phonetic: "a way hma", meaning: "远处", example: "ရုံးက အဝေးမှာလား။", exampleCn: "办公室远吗？" },
  { id: 121, word: "တည့်တည့်", phonetic: "te de", meaning: "直走", example: "တည့်တည့် သွားပါ။", exampleCn: "请直走。" },
  { id: 122, word: "ကွေ့ပါ", phonetic: "kwe ba", meaning: "请转弯", example: "ရှေ့မှာ ညာဘက်ကို ကွေ့ပါ။", exampleCn: "前面请右转。" },
  { id: 123, word: "အပေါ်ထပ်", phonetic: "a paw htat", meaning: "楼上", example: "အပေါ်ထပ်ကို သွားပါ။", exampleCn: "请去楼上。" },
  { id: 124, word: "အောက်ထပ်", phonetic: "auk htat", meaning: "楼下", example: "အောက်ထပ်မှာ ပေးချေပါ။", exampleCn: "请在楼下付款。" },
  { id: 125, word: "တံခါး", phonetic: "ta ga", meaning: "门", example: "တံခါး ဘေးမှာ စောင့်ပါ။", exampleCn: "请在门旁边等。" },
  { id: 126, word: "လမ်း", phonetic: "lan", meaning: "路 / 街道", example: "ဒီလမ်းကနေ သွားပါ။", exampleCn: "请从这条路走。" },
  { id: 127, word: "ကား", phonetic: "ka", meaning: "车", example: "ကား ရှိပါသလား။", exampleCn: "有车吗？" },
  { id: 128, word: "ဆိုင်ကယ်", phonetic: "hsai ke", meaning: "摩托车", example: "ဆိုင်ကယ်နဲ့ သွားလို့ရမလား။", exampleCn: "可以骑摩托车去吗？" },
  { id: 129, word: "လမ်းလျှောက်", phonetic: "lan shauk", meaning: "走路", example: "လမ်းလျှောက် သွားလို့ရပါတယ်။", exampleCn: "可以走路去。" },
  { id: 130, word: "ဘယ်လောက်ကြာမလဲ", phonetic: "be lauk kya ma le", meaning: "要多久", example: "ရုံးကို ဘယ်လောက်ကြာမလဲ။", exampleCn: "去办公室要多久？" },
  { id: 131, word: "ငါးမိနစ်", phonetic: "nga mi nit", meaning: "五分钟", example: "ငါးမိနစ် စောင့်ပါ။", exampleCn: "请等五分钟。" },
  { id: 132, word: "တစ်နာရီ", phonetic: "ta na yi", meaning: "一小时", example: "တစ်နာရီ ကြာပါမယ်။", exampleCn: "需要一个小时。" },
  { id: 133, word: "စျေးနှုန်း", phonetic: "zay hnon", meaning: "价格", example: "စျေးနှုန်း ဘယ်လောက်လဲ။", exampleCn: "价格是多少？" },
  { id: 134, word: "လက်ခံပါတယ်", phonetic: "let khan ba de", meaning: "接受", example: "ဘဏ်ကတ် လက်ခံပါသလား။", exampleCn: "接受银行卡吗？" },
  { id: 135, word: "မလက်ခံပါဘူး", phonetic: "ma let khan ba bu", meaning: "不接受", example: "ကတ် မလက်ခံပါဘူး။", exampleCn: "不接受银行卡。" },
  { id: 136, word: "အကြွေ", phonetic: "a kywe", meaning: "零钱", example: "အကြွေ ရှိပါသလား။", exampleCn: "有零钱吗？" },
  { id: 137, word: "ပိုက်ဆံ", phonetic: "paik hsan", meaning: "钱", example: "ပိုက်ဆံ လုံလောက်ပါသလား။", exampleCn: "钱够吗？" },
  { id: 138, word: "ပြန်အမ်းငွေ", phonetic: "pyan an ngwe", meaning: "找零 / 退款", example: "ပြန်အမ်းငွေ ပေးပါ။", exampleCn: "请给我找零/退款。" },
  { id: 139, word: "ဝယ်ချင်ပါတယ်", phonetic: "we chin ba de", meaning: "想买", example: "ဒီဟာ ဝယ်ချင်ပါတယ်။", exampleCn: "我想买这个。" },
  { id: 140, word: "ကြည့်ချင်ပါတယ်", phonetic: "kyi chin ba de", meaning: "想看", example: "နောက်တစ်ခု ကြည့်ချင်ပါတယ်။", exampleCn: "我想看另一个。" },
  { id: 141, word: "မှာချင်ပါတယ်", phonetic: "hma chin ba de", meaning: "想点 / 想订", example: "ထမင်း မှာချင်ပါတယ်။", exampleCn: "我想点米饭。" },
  { id: 142, word: "ထမင်း", phonetic: "hta min", meaning: "米饭 / 饭", example: "ထမင်း တစ်ပွဲ ပေးပါ။", exampleCn: "请给我一份米饭。" },
  { id: 143, word: "ဟင်း", phonetic: "hin", meaning: "菜 / 咖喱", example: "ဟင်း ဘာရှိပါသလဲ။", exampleCn: "有什么菜？" },
  { id: 144, word: "ရေနွေး", phonetic: "ye nway", meaning: "热水", example: "ရေနွေး ပေးပါ။", exampleCn: "请给我热水。" },
  { id: 145, word: "ရေအေး", phonetic: "ye ay", meaning: "冷水", example: "ရေအေး ရှိပါသလား။", exampleCn: "有冷水吗？" },
  { id: 146, word: "မစားဘူး", phonetic: "ma sa bu", meaning: "不吃", example: "ငရုတ်သီး မစားဘူး။", exampleCn: "我不吃辣椒。" },
  { id: 147, word: "စားလို့ရပါတယ်", phonetic: "sa lo ya ba de", meaning: "可以吃", example: "ဒီဟာ စားလို့ရပါတယ်။", exampleCn: "这个可以吃。" },
  { id: 148, word: "အစပ်", phonetic: "a sat", meaning: "辣", example: "အစပ် မလိုပါဘူး။", exampleCn: "不要辣。" },
  { id: 149, word: "ချိုပါတယ်", phonetic: "cho ba de", meaning: "甜", example: "ဒီဟာ ချိုပါတယ်။", exampleCn: "这个很甜。" },
  { id: 150, word: "အေးပါတယ်", phonetic: "ay ba de", meaning: "冷 / 凉", example: "ရေ အေးပါတယ်။", exampleCn: "水是凉的。" }
];
