window.WORDS = [
  { id: 1, word: "မင်္ဂလာပါ", phonetic: "mingalaba", meaning: "你好", example: "မင်္ဂလာပါ၊ ကျွန်တော် အကူအညီ လိုပါတယ်။", exampleCn: "你好，我需要帮助。" },
  { id: 2, word: "ကျေးဇူးတင်ပါတယ်", phonetic: "ce zu tin ba de", meaning: "谢谢", example: "သင့်အကူအညီအတွက် ကျေးဇူးတင်ပါတယ်။", exampleCn: "谢谢你的帮助。" },
  { id: 3, word: "တောင်းပန်ပါတယ်", phonetic: "taung pan ba de", meaning: "对不起", example: "နောက်ကျသွားလို့ တောင်းပန်ပါတယ်။", exampleCn: "我迟到了，对不起。" },
  { id: 4, word: "ဟုတ်ကဲ့", phonetic: "hou ke", meaning: "是的 / 好的", example: "ဟုတ်ကဲ့၊ နားလည်ပါတယ်။", exampleCn: "好的，我明白了。" },
  { id: 5, word: "မဟုတ်ပါဘူး", phonetic: "ma hou ba bu", meaning: "不是", example: "ဒါ ကျွန်တော့်စာရွက် မဟုတ်ပါဘူး။", exampleCn: "这不是我的文件。" },
  { id: 6, word: "နားလည်ပါတယ်", phonetic: "na le ba de", meaning: "明白", example: "သင်ပြောတာ နားလည်ပါတယ်။", exampleCn: "我明白你说的话。" },
  { id: 7, word: "နားမလည်ပါဘူး", phonetic: "na ma le ba bu", meaning: "不明白", example: "မြန်မာလို နားမလည်ပါဘူး။", exampleCn: "我不太懂缅语。" },
  { id: 8, word: "ဖြည်းဖြည်း ပြောပါ", phonetic: "hpye hpye pyaw ba", meaning: "请慢一点说", example: "ကျေးဇူးပြုပြီး ဖြည်းဖြည်း ပြောပါ။", exampleCn: "请慢一点说。" },
  { id: 9, word: "ထပ်ပြောပါ", phonetic: "htat pyaw ba", meaning: "请再说一遍", example: "တစ်ခါ ထပ်ပြောပါ။", exampleCn: "请再说一遍。" },
  { id: 10, word: "ဘယ်မှာလဲ", phonetic: "be hma le", meaning: "在哪里", example: "ရုံး ဘယ်မှာလဲ။", exampleCn: "办公室在哪里？" },
  { id: 11, word: "ဘယ်လောက်လဲ", phonetic: "be lauk le", meaning: "多少钱", example: "ဒီဟာ ဘယ်လောက်လဲ။", exampleCn: "这个多少钱？" },
  { id: 12, word: "လိုချင်ပါတယ်", phonetic: "lo chin ba de", meaning: "想要", example: "ရေတစ်ဘူး လိုချင်ပါတယ်။", exampleCn: "我想要一瓶水。" },
  { id: 13, word: "မလိုပါဘူး", phonetic: "ma lo ba bu", meaning: "不需要", example: "အိတ် မလိုပါဘူး။", exampleCn: "我不需要袋子。" },
  { id: 14, word: "အကူအညီ", phonetic: "a ku a nyi", meaning: "帮助", example: "အကူအညီ ပေးနိုင်မလား။", exampleCn: "可以帮我吗？" },
  { id: 15, word: "ရုံး", phonetic: "yone", meaning: "办公室 / 政府部门", example: "အစိုးရရုံးကို သွားချင်ပါတယ်။", exampleCn: "我想去政府办公室。" },
  { id: 16, word: "စာရွက်စာတမ်း", phonetic: "sa ywet sa dan", meaning: "文件 / 材料", example: "စာရွက်စာတမ်းတွေ ပြင်ဆင်ထားပါတယ်။", exampleCn: "文件材料已经准备好了。" },
  { id: 17, word: "နိုင်ငံကူးလက်မှတ်", phonetic: "naing ngan ku let hmat", meaning: "护照", example: "နိုင်ငံကူးလက်မှတ် ပြချင်ပါတယ်။", exampleCn: "我想出示护照。" },
  { id: 18, word: "မှတ်ပုံတင်", phonetic: "hmat pone tin", meaning: "身份证 / 登记", example: "မှတ်ပုံတင် မိတ္တူ လိုပါသလား။", exampleCn: "需要身份证复印件吗？" },
  { id: 19, word: "လက်မှတ်", phonetic: "let hmat", meaning: "签名 / 票", example: "ဒီနေရာမှာ လက်မှတ်ထိုးပါ။", exampleCn: "请在这里签名。" },
  { id: 20, word: "ဖောင်", phonetic: "hpoung", meaning: "表格", example: "ဒီဖောင်ကို ဖြည့်ရမလား။", exampleCn: "需要填写这张表吗？" },
  { id: 21, word: "မိတ္တူ", phonetic: "mi tu", meaning: "复印件", example: "မိတ္တူ နှစ်စောင် လိုပါတယ်။", exampleCn: "需要两份复印件。" },
  { id: 22, word: "တန်းစီ", phonetic: "tan si", meaning: "排队", example: "ဒီမှာ တန်းစီရပါမယ်။", exampleCn: "需要在这里排队。" },
  { id: 23, word: "နံပါတ်", phonetic: "nan bat", meaning: "号码", example: "ကျွန်တော့်နံပါတ် ဘယ်အချိန်ခေါ်မလဲ။", exampleCn: "什么时候叫到我的号码？" },
  { id: 24, word: "အခန်း", phonetic: "a khan", meaning: "房间", example: "အခန်း နံပါတ် သုံးကို သွားပါ။", exampleCn: "请去三号房间。" },
  { id: 25, word: "အခကြေးငွေ", phonetic: "a kha cye ngwe", meaning: "费用", example: "အခကြေးငွေ ဘယ်လောက်ပေးရမလဲ။", exampleCn: "需要交多少费用？" },
  { id: 26, word: "ငွေသား", phonetic: "ngwe tha", meaning: "现金", example: "ငွေသားနဲ့ ပေးလို့ရမလား။", exampleCn: "可以用现金支付吗？" },
  { id: 27, word: "ဘဏ်ကတ်", phonetic: "ban kat", meaning: "银行卡", example: "ဘဏ်ကတ်နဲ့ ပေးလို့ရပါသလား။", exampleCn: "可以用银行卡支付吗？" },
  { id: 28, word: "လိပ်စာ", phonetic: "leik sa", meaning: "地址", example: "လိပ်စာကို ဒီမှာရေးပါ။", exampleCn: "请把地址写在这里。" },
  { id: 29, word: "ဖုန်းနံပါတ်", phonetic: "phone nan bat", meaning: "电话号码", example: "ဖုန်းနံပါတ် ထားခဲ့ပါ။", exampleCn: "请留下电话号码。" },
  { id: 30, word: "ချိန်းဆိုချက်", phonetic: "chein so chet", meaning: "预约", example: "မနက်ဖြန် ချိန်းဆိုချက် ရှိပါတယ်။", exampleCn: "我明天有预约。" },
  { id: 31, word: "ယနေ့", phonetic: "ya nei", meaning: "今天", example: "ယနေ့ လုပ်လို့ရမလား။", exampleCn: "今天可以办理吗？" },
  { id: 32, word: "မနက်ဖြန်", phonetic: "ma net hpyan", meaning: "明天", example: "မနက်ဖြန် ပြန်လာပါမယ်။", exampleCn: "我明天再来。" },
  { id: 33, word: "အခု", phonetic: "a khu", meaning: "现在", example: "အခု စောင့်ရမလား။", exampleCn: "现在需要等吗？" },
  { id: 34, word: "စောင့်ပါ", phonetic: "saung ba", meaning: "请等待", example: "ခဏ စောင့်ပါ။", exampleCn: "请稍等。" },
  { id: 35, word: "ပြီးပြီ", phonetic: "pi bi", meaning: "完成了", example: "လုပ်ငန်းစဉ် ပြီးပြီလား။", exampleCn: "流程完成了吗？" },
  { id: 36, word: "မပြီးသေးပါဘူး", phonetic: "ma pi thay ba bu", meaning: "还没完成", example: "ဖောင် မပြီးသေးပါဘူး။", exampleCn: "表格还没填完。" },
  { id: 37, word: "ဆေးရုံ", phonetic: "hsay yone", meaning: "医院", example: "ဆေးရုံကို သွားချင်ပါတယ်။", exampleCn: "我想去医院。" },
  { id: 38, word: "ရဲစခန်း", phonetic: "ye sa khan", meaning: "警察局", example: "ရဲစခန်း ဘယ်မှာလဲ။", exampleCn: "警察局在哪里？" },
  { id: 39, word: "စျေး", phonetic: "zay", meaning: "市场", example: "စျေးကို ဘယ်လိုသွားရမလဲ။", exampleCn: "市场怎么走？" },
  { id: 40, word: "ဘတ်စ်ကား", phonetic: "bat ka", meaning: "公交车", example: "ဘတ်စ်ကားမှတ်တိုင် ဘယ်မှာလဲ။", exampleCn: "公交车站在哪里？" },
  { id: 41, word: "တက္ကစီ", phonetic: "taxi", meaning: "出租车", example: "တက္ကစီ ခေါ်ပေးပါ။", exampleCn: "请帮我叫出租车。" },
  { id: 42, word: "မှတ်တိုင်", phonetic: "hmat taing", meaning: "车站", example: "နောက်မှတ်တိုင်မှာ ဆင်းပါမယ်။", exampleCn: "我在下一站下车。" },
  { id: 43, word: "ရေ", phonetic: "ye", meaning: "水", example: "ရေ တစ်ခွက် ပေးပါ။", exampleCn: "请给我一杯水。" },
  { id: 44, word: "အစားအစာ", phonetic: "a sa a sa", meaning: "食物", example: "အစားအစာ မှာချင်ပါတယ်။", exampleCn: "我想点食物。" },
  { id: 45, word: "မနက်စာ", phonetic: "ma net sa", meaning: "早餐", example: "မနက်စာ ရှိပါသလား။", exampleCn: "有早餐吗？" },
  { id: 46, word: "အိမ်သာ", phonetic: "ein tha", meaning: "厕所", example: "အိမ်သာ ဘယ်မှာလဲ။", exampleCn: "厕所在哪里？" },
  { id: 47, word: "ဈေးကြီးတယ်", phonetic: "zay gyi de", meaning: "太贵了", example: "နည်းနည်း ဈေးကြီးတယ်။", exampleCn: "有点贵。" },
  { id: 48, word: "လျှော့ပေးပါ", phonetic: "shaut pay ba", meaning: "请便宜一点", example: "နည်းနည်း လျှော့ပေးပါ။", exampleCn: "请便宜一点。" },
  { id: 49, word: "အရေးကြီးပါတယ်", phonetic: "a yay gyi ba de", meaning: "很重要", example: "ဒီစာရွက် အရေးကြီးပါတယ်။", exampleCn: "这份文件很重要。" },
  { id: 50, word: "အရေးပေါ်", phonetic: "a yay paw", meaning: "紧急", example: "အရေးပေါ် အကူအညီ လိုပါတယ်။", exampleCn: "我需要紧急帮助。" }
];
